src/main/kotlin/app/termora/tlog/TerminalLoggerAction.kt, src/main/kotlin/app/termora/tlog/TerminalLoggerDataListener.kt
“终端日志” 是全局开关，当开启后所有的 “终端” 窗口日志都会被单独记录到各自的文件中，文件存储在 `~/.termora/terminal/logs/yyyy-MM-dd/${host.name}.HH_mm_ss_SSS.log` 中。
**一旦 “开始记录” 除非手动停止否则记录所有操作记录，日志文件不会自动清除**
当用户 “开始记录” 时并不会创建日志文件，而是 [VisualTerminal.kt](https://github.com/TermoraDev/termora/blob/1.0.1/src/main/kotlin/app/termora/terminal/VisualTerminal.kt#L52) 发送后会立即创建日志文件。
当用户关闭终端标签页或“停止记录”时，会自动关闭文件流。如果用户再次 “开始记录“ 会重新创建一个日志文件重复此流程
=> feat: 当停止记录终端日志的时候立即关闭文件流

src/main/kotlin/app/termora/terminal/ControlSequenceIntroducerProcessor.kt
修复 #23 问题。
该问题出现是因为收到了 `ESC[?4m` 私有模式导致的。在 XTerm 协议中 `ESC[4m` 是添加下划线，因为忽略了 `?` 导致意外出现下划线的问题。
=> fix: 修复 ESC[?xm 私有模式导致不正常渲染的问题

src/main/kotlin/app/termora/SettingsOptionsPane.kt
=> fix: 修复在同步配置时 “宏” 没有禁用的问题

src/main/kotlin/app/termora/transport/FileSystemPanel.kt, src/main/kotlin/app/termora/transport/TransportManager.kt
=> fix: 修复 SFTP 拖拽单个文件上传失败的问题

src/main/kotlin/app/termora/terminal/panel/TerminalPanel.kt, src/main/kotlin/app/termora/terminal/panel/TerminalPanelKeyAdapter.kt, src/main/kotlin/app/termora/terminal/panel/TerminalWindowsCopyAction.kt, src/main/kotlin/app/termora/terminal/panel/TerminalWindowsPasteAction.kt
对于终端界面，如果要发送功能键必须按住 `Ctrl` 。例如：`Ctrl + C` 是中断操作，`Ctrl + Shift + C` 是不能发送中断操作的。
=> feat: Windows keyboard shortcut

src/main/kotlin/app/termora/terminal/panel/TerminalPanelKeyAdapter.kt
在 Windows 情况下当执行 `Ctrl + L/Any key` 时，如果触发了快捷键，那么终端不应该处理这个输入。
=> fix: shortcut keys lead to terminal input

src/main/kotlin/app/termora/ApplicationRunner.kt
=> fix: theAwtToolkitWindow

src/main/kotlin/app/termora/MyTabbedPane.kt, src/main/kotlin/app/termora/TermoraFrame.kt, src/main/kotlin/app/termora/actions/DataProviders.kt
=> feat: support drag and drop to other windows

src/main/kotlin/app/termora/MyTabbedPane.kt
如果拖拽释放时，鼠标下没有 TermoraFrame 那么则创建一个新窗口并将拖拽的 Tab 移动过去。
=> feat: external release to create a new window

build.gradle.kts
=> chore: opengl

src/main/kotlin/app/termora/keymap/KeymapManager.kt, src/main/resources/i18n/messages.properties, src/main/resources/i18n/messages_zh_CN.properties, src/main/resources/i18n/messages_zh_TW.properties
#183
将双击 Shift 快捷键声明为废弃，会在未来的版本中删除。
----
双击 Shift 打开 FindEverywhere 在终端应用中并不合适，用户应该用 `Command + T / Ctrl + T` 或其它自定义快捷键代替。
=> feat: deprecate double-click Shift shortcut

src/main/kotlin/app/termora/Application.kt, src/main/kotlin/app/termora/ApplicationRunner.kt, src/main/kotlin/app/termora/Host.kt, src/main/kotlin/app/termora/HostTree.kt, src/main/kotlin/app/termora/PtyConnectorFactory.kt, src/main/kotlin/app/termora/PtyHostTerminalTab.kt, src/main/kotlin/app/termora/SFTPPtyTerminalTab.kt, src/main/kotlin/app/termora/TerminalTabbed.kt, src/main/kotlin/app/termora/actions/OpenHostAction.kt, src/main/kotlin/app/termora/transport/FileSystemPanel.kt, src/main/kotlin/app/termora/transport/SFTPAction.kt, src/main/resources/i18n/messages.properties, src/main/resources/i18n/messages_zh_CN.properties, src/main/resources/i18n/messages_zh_TW.properties
默认会执行 `sftp` 终端命令，如果电脑上没有 `sftp` 应用那么会报错，在 Unix 系统下通常自带 `sftp` 命令。
Windows 11 下应该是自带 `sftp` 的，如果你的电脑没有 `sftp` 那么安装后配置到环境变量即可使用此功能。
打开默认终端，执行 `sftp` 回车即可。
----
<br/>
=> feat: SFTP command

src/main/kotlin/app/termora/actions/TerminalClearScreenAction.kt, src/main/kotlin/app/termora/keymap/KeymapTableModel.kt, src/main/resources/i18n/messages.properties, src/main/resources/i18n/messages_zh_CN.properties, src/main/resources/i18n/messages_zh_TW.properties
在 macOS 上执行 `Shift + Command + L` ，在 Windows/Linux 上执行 `Shift + Ctrl + L` 可以清除终端屏幕
=> feat: clear terminal screen shortcut

src/main/kotlin/app/termora/Host.kt, src/main/kotlin/app/termora/HostTerminalTab.kt, src/main/kotlin/app/termora/PtyHostTerminalTab.kt, src/main/kotlin/app/termora/SFTPPtyTerminalTab.kt, src/main/kotlin/app/termora/TerminalTabbed.kt, src/main/kotlin/app/termora/terminal/DataKey.kt, src/main/kotlin/app/termora/terminal/OperatingSystemCommandProcessor.kt
通过 [OSC 1337](https://iterm2.com/documentation-escape-codes.html) 可以让 Termora 感知到当前工作目录，当进入 `SFTP Command` 可以自动切换到当前 Shell 的工作目录。
要想让 Termora 获取到当前工作目录需要提前配置一些脚本，否则无法正常工作。
`~/.bash_profile`:
```bash
export PS1="$PS1\[\e]1337;CurrentDir="'$(pwd)\a\]'
```
`~/.zshrc`:
```bash
precmd () { echo -n "\x1b]1337;CurrentDir=$(pwd)\x07" }
```
`~/.config/fish/config.fish`:
```bash
function __termora_working_directory_reporting --on-event fish_prompt
echo -en "\e]1337;CurrentDir=$PWD\x7"
end
```
注意：当配置完之后，需要重新打开 `SSH` 连接才能生效。
=> feat: osc 1337

src/main/kotlin/app/termora/Database.kt, src/main/kotlin/app/termora/SFTPPtyTerminalTab.kt, src/main/kotlin/app/termora/SettingsOptionsPane.kt
#263
<br/>
支持自定义 `sftp` 路径，让用户自定义选择 `sftp` 程序以解决 `Tab` 无法补全的问题。
=> feat: support setting sftp path

THIRDPARTY, build.gradle.kts, gradle/libs.versions.toml, src/main/kotlin/app/termora/HostManager.kt, src/main/kotlin/app/termora/HostTreeNode.kt, src/main/kotlin/app/termora/NewHostTree.kt, src/main/kotlin/app/termora/NewHostTreeModel.kt, src/main/kotlin/app/termora/SFTPPtyTerminalTab.kt, src/main/kotlin/app/termora/SSHTerminalTab.kt, src/main/kotlin/app/termora/SshClients.kt, src/main/kotlin/app/termora/TerminalTabbed.kt, src/main/kotlin/app/termora/transport/SFTPAction.kt, src/main/kotlin/app/termora/transport/SftpFileSystemPanel.kt, src/main/resources/i18n/messages.properties, src/main/resources/i18n/messages_zh_CN.properties, src/main/resources/i18n/messages_zh_TW.properties
#193
template: [termora_import.csv](https://github.com/user-attachments/files/18919839/termora_import.csv)
=> feat: supports importing hosts from CSV

src/main/kotlin/app/termora/TermoraFrameManager.kt
=> feat: supports remembering window positions

src/main/java/app/termora/MyFlatTabbedPaneUI.java, src/main/kotlin/app/termora/MyTabbedPane.kt
<br/>
如果在 `JTabbedPane` 的 `Tab` 组件上加上 `putClientProperty(FlatClientProperties.TABBED_PANE_HAS_FULL_BORDER, true)` 即可渲染完整的边框（图2）。
=> feat: improve FlatTabbedPaneUI

src/main/resources/termora.iss
#557
对于 Windows 安装前，会删除安装目录下的 `{app}\bin\*.jar` 和 `{app}\runtime\*` 文件或文件夹
对于上述规则以外的文件/文件夹不做处理
=> fix: delete leftover files before installing Windows

src/main/kotlin/app/termora/keymgr/KeyManagerPanel.kt
在导入密钥时，`ohKeyPair.remark`只有在初始化时被赋值，并不会被输入框后续修改过的新值更新。
=> fix: missing remark when importing keys

src/main/kotlin/app/termora/HostDialog.kt, src/main/kotlin/app/termora/OptionsPane.kt, src/main/kotlin/app/termora/SettingsDialog.kt, src/main/kotlin/app/termora/SettingsOptionsPane.kt
打开`设置`面板时，会一次性加载所有选项，当遇到需要加载很久的面板时，如需要加载非常多的字体的`终端`，会非常影响体验。
这个PR实现了打开面板时选项的懒加载，只有被选中时才会加载的同时，对字体的单选框也实现了懒加载。
=> perf: lazy loading `OptionsPane` and `Fonts`
