src/main/kotlin/app/termora/Laf.kt, src/main/kotlin/app/termora/ThemeManager.kt
=> feat: support Dracula

src/main/kotlin/app/termora/TerminalTabbed.kt
=> chore: 在新窗口中打开时标题跟随之前的

src/main/kotlin/app/termora/terminal/panel/TerminalPanelMouseTrackingAdapter.kt
=> feat: vim 支持鼠标滚动

src/main/kotlin/app/termora/terminal/panel/TerminalPanelKeyAdapter.kt
=> fix: 修复 Windows 切换标签页导致误输入的问题

src/main/kotlin/app/termora/TermoraFrame.kt
=> feat: 弹窗位置以父窗口为中心

src/main/kotlin/app/termora/EditHostOptionsPane.kt, src/main/kotlin/app/termora/HostOptionsPane.kt, src/main/kotlin/app/termora/HostTreeDialog.kt, src/main/kotlin/app/termora/SshClients.kt, src/main/kotlin/app/termora/WelcomePanel.kt, src/main/resources/i18n/messages.properties, src/main/resources/i18n/messages_zh_CN.properties, src/main/resources/i18n/messages_zh_TW.properties
=> feat: support jump hosts

src/main/kotlin/app/termora/Database.kt, src/main/kotlin/app/termora/SettingsOptionsPane.kt, src/main/kotlin/app/termora/actions/SettingsAction.kt, src/main/kotlin/app/termora/keymap/Keymap.kt, src/main/kotlin/app/termora/sync/GitSyncer.kt, src/main/kotlin/app/termora/sync/SyncConfig.kt
=> feat: support keymap sync

src/main/java/app/termora/SwingUtils.java, src/main/kotlin/app/termora/ApplicationRunner.kt, src/main/kotlin/app/termora/Database.kt, src/main/kotlin/app/termora/DialogWrapper.kt, src/main/kotlin/app/termora/Laf.kt, src/main/kotlin/app/termora/SettingsOptionsPane.kt, src/main/kotlin/app/termora/ThemeManager.kt
=> feat: theme sync with OS

src/main/kotlin/app/termora/SSHTerminalTab.kt, src/main/kotlin/app/termora/TerminalTabDialog.kt, src/main/kotlin/app/termora/TerminalTabbed.kt, src/main/kotlin/app/termora/WelcomePanel.kt, src/main/kotlin/app/termora/actions/ActionManager.kt, src/main/kotlin/app/termora/actions/DataProviders.kt, src/main/kotlin/app/termora/actions/TabReconnectAction.kt, src/main/kotlin/app/termora/keymap/KeyShortcut.kt, src/main/kotlin/app/termora/keymap/KeymapImpl.kt, src/main/kotlin/app/termora/keymap/KeymapPanel.kt, src/main/kotlin/app/termora/keymap/KeymapTableModel.kt
=> feat: support fast reconnect

src/main/kotlin/app/termora/EditHostOptionsPane.kt, src/main/kotlin/app/termora/HostOptionsPane.kt, src/main/kotlin/app/termora/HostTree.kt, src/main/kotlin/app/termora/TextField.kt
=> feat: improved keyPair comboBox

src/main/kotlin/app/termora/terminal/KeyEncoderImpl.kt
=> feat: left right key

src/main/kotlin/app/termora/PtyConnectorReader.kt, src/main/kotlin/app/termora/PtyHostTerminalTab.kt, src/main/kotlin/app/termora/terminal/ControlSequenceIntroducerProcessor.kt, src/main/kotlin/app/termora/terminal/DataKey.kt, src/main/kotlin/app/termora/terminal/PtyProcessConnector.kt
=> feat: Device Status Report (DSR)

src/main/kotlin/app/termora/terminal/panel/TerminalPanelKeyAdapter.kt
=> fix: tab key not working

build.gradle.kts
=> feat: xcrun stapler staple

src/main/kotlin/app/termora/keymgr/KeyManager.kt
=> fix: key manager

src/main/kotlin/app/termora/HostOptionsPane.kt
=> fix: issue 112

src/main/kotlin/app/termora/MyTabbedPane.kt, src/main/kotlin/app/termora/TerminalTabbed.kt, src/main/kotlin/app/termora/TerminalTabbedManager.kt, src/main/kotlin/app/termora/TermoraFrame.kt
=> feat: support drag and drop sorting

src/main/kotlin/app/termora/transport/FileSystemTableModel.kt, src/main/resources/i18n/messages.properties, src/main/resources/i18n/messages_zh_CN.properties, src/main/resources/i18n/messages_zh_TW.properties
=> fix: sftp symbolic link

src/main/kotlin/app/termora/HostDialog.kt
=> fix: host test connection

src/main/kotlin/app/termora/keymap/KeymapManager.kt
一开始是后置判断，也就是组件处理完之后再判断是不是全局快捷键，这样的坏处就是会导致终端输入问题。虽然在终端那里判断了是不是快捷键，这样显然不够优雅。
前置判断通过 `getConditionForKeyStroke` 查看组件是否注册了快捷键，如果已经注册了快捷键那么不会处理。
如果终端的某个键组合是快捷键，那么不会发送到终端，因为已经被快捷键给前置拦截了。
=> feat: shortcut key prediction

src/main/kotlin/app/termora/MyTabbedPane.kt
=> feat: press and hold Shift to close Tab

src/main/kotlin/app/termora/MyTabbedPane.kt, src/main/kotlin/app/termora/TerminalTabbed.kt
=> chore: remove tabbed hover background

src/main/kotlin/app/termora/HostTree.kt, src/main/kotlin/app/termora/MyTabbedPane.kt, src/main/resources/i18n/messages.properties
=> feat: open in new window

THIRDPARTY, build.gradle.kts, gradle/libs.versions.toml, src/main/kotlin/app/termora/ChannelShellPtyConnector.kt, src/main/kotlin/app/termora/EditHostOptionsPane.kt, src/main/kotlin/app/termora/Host.kt, src/main/kotlin/app/termora/HostDialog.kt, src/main/kotlin/app/termora/HostOptionsPane.kt, src/main/kotlin/app/termora/HostTree.kt, src/main/kotlin/app/termora/Icons.kt, src/main/kotlin/app/termora/Main.kt, src/main/kotlin/app/termora/PtyHostTerminalTab.kt, src/main/kotlin/app/termora/SerialPortPtyConnector.kt, src/main/kotlin/app/termora/SerialTerminalTab.kt, src/main/kotlin/app/termora/Serials.kt, src/main/kotlin/app/termora/actions/OpenHostAction.kt, src/main/kotlin/app/termora/terminal/ControlSequenceIntroducerProcessor.kt, src/main/kotlin/app/termora/terminal/PtyConnector.kt, src/main/kotlin/app/termora/terminal/PtyConnectorDelegate.kt, src/main/kotlin/app/termora/terminal/PtyProcessConnector.kt, src/main/kotlin/app/termora/terminal/panel/TerminalPanel.kt, src/main/kotlin/app/termora/terminal/panel/TerminalPanelKeyAdapter.kt, src/main/kotlin/app/termora/terminal/panel/TerminalPanelMouseTrackingAdapter.kt, src/main/resources/i18n/messages.properties, src/main/resources/i18n/messages_zh_CN.properties, src/main/resources/i18n/messages_zh_TW.properties, src/main/resources/icons/plugin.svg, src/main/resources/icons/plugin_dark.svg
=> feat: serial comm

src/main/kotlin/app/termora/terminal/panel/TerminalDisplay.kt
=> chore: text cursor

src/main/kotlin/app/termora/TextField.kt
Allows copy and cut operations in PasswordField
=> chore: PasswordField allows copying and cutting

src/main/kotlin/app/termora/SettingsOptionsPane.kt, src/main/kotlin/app/termora/sync/GitSyncer.kt, src/main/kotlin/app/termora/sync/SafetySyncer.kt, src/main/kotlin/app/termora/sync/SyncConfig.kt, src/main/kotlin/app/termora/sync/SyncerProvider.kt, src/main/kotlin/app/termora/sync/WebDAVSyncer.kt, src/main/resources/i18n/messages.properties, src/main/resources/i18n/messages_zh_CN.properties, src/main/resources/i18n/messages_zh_TW.properties
=> Support for WebDAV

src/main/kotlin/app/termora/Database.kt, src/main/kotlin/app/termora/Icons.kt, src/main/kotlin/app/termora/SettingsOptionsPane.kt, src/main/kotlin/app/termora/TerminalFactory.kt, src/main/resources/i18n/messages.properties, src/main/resources/i18n/messages_zh_CN.properties, src/main/resources/i18n/messages_zh_TW.properties, src/main/resources/icons/run.svg, src/main/resources/icons/run_dark.svg
Support for turning off beep, it is on by default.
=> feat: support for turning off beep

src/main/kotlin/app/termora/transport/FileSystemPanel.kt
=> feat: support drag and drop transfer

src/main/kotlin/app/termora/terminal/ControlSequenceIntroducerProcessor.kt, src/main/kotlin/app/termora/terminal/CursorStoreStores.kt, src/main/kotlin/app/termora/terminal/EscapeSequenceProcessor.kt
=> fix: color mismatch issue

src/main/kotlin/app/termora/TermoraFrameManager.kt, src/main/resources/i18n/messages.properties, src/main/resources/i18n/messages_zh_CN.properties, src/main/resources/i18n/messages_zh_TW.properties, src/test/resources/sshd/Dockerfile
=> feat: confirmation required to exit program

.github/workflows/winget.yml
=> feat: winget releaser

src/main/kotlin/app/termora/terminal/panel/TerminalPanel.kt
=> fix: line breaks

src/main/kotlin/app/termora/PtyHostTerminalTab.kt, src/main/kotlin/app/termora/TerminalFactory.kt, src/main/kotlin/app/termora/TerminalPanelFactory.kt, src/main/kotlin/app/termora/keymgr/KeyManagerPanel.kt, src/main/kotlin/app/termora/keymgr/SSHCopyIdDialog.kt, src/main/kotlin/app/termora/terminal/panel/TerminalPanel.kt, src/main/resources/i18n/messages.properties, src/main/resources/i18n/messages_zh_CN.properties, src/main/resources/i18n/messages_zh_TW.properties
=> feat: support ssh-copy-id

src/main/kotlin/app/termora/terminal/panel/TerminalPanel.kt
=> fix: encoding error

src/main/kotlin/app/termora/keymgr/KeyManagerPanel.kt, src/main/kotlin/app/termora/keymgr/SSHCopyIdDialog.kt
=> feat: copy public key display name

src/main/kotlin/app/termora/SshClients.kt
=> fix: SSH password authentication reading local private key

src/main/kotlin/app/termora/keyboardinteractive/TerminalUserInteraction.kt
=> fix: center the MFA Code dialog

src/main/kotlin/app/termora/HostTree.kt
=> feat: HostTree shows more information

src/main/kotlin/app/termora/OptionPane.kt, src/main/kotlin/app/termora/SSHTerminalTab.kt, src/main/kotlin/app/termora/SshClients.kt, src/main/kotlin/app/termora/transport/SftpFileSystemPanel.kt, src/main/resources/i18n/messages.properties, src/main/resources/i18n/messages_zh_CN.properties, src/main/resources/i18n/messages_zh_TW.properties
=> feat: known_hosts

src/main/kotlin/app/termora/RequestAuthenticationDialog.kt, src/main/kotlin/app/termora/SSHTerminalTab.kt, src/main/kotlin/app/termora/transport/SftpFileSystemPanel.kt
=> feat: supports one-time authorised connection

src/main/kotlin/app/termora/terminal/CursorStore.kt, src/main/kotlin/app/termora/terminal/CursorStoreStores.kt
=> fix: auto wrap mode

src/main/kotlin/app/termora/SettingsOptionsPane.kt, src/main/resources/i18n/messages.properties, src/main/resources/i18n/messages_zh_CN.properties, src/main/resources/i18n/messages_zh_TW.properties
=> feat: export configuration file support encryption

src/main/kotlin/app/termora/MyTabbedPane.kt
=> fix: tab drag

src/main/kotlin/app/termora/TermoraToolBar.kt
#225 
在 Windows 和 Linux 系统上预留空间方便拖动窗口
=> chore: toolbar strut

src/main/kotlin/app/termora/transport/FileSystemPanel.kt, src/main/resources/i18n/messages.properties, src/main/resources/i18n/messages_zh_CN.properties, src/main/resources/i18n/messages_zh_TW.properties
如果在 Linux 环境没有配置 “编辑命令” 那么在 “编辑” 时提醒。
=> chore: optimising SFTP for Linux edit

src/main/kotlin/app/termora/transport/FileSystemPanel.kt
当编辑 SFTP 文件时，会在本地生成一个临时文件，如果这个临时文件被删除那么则停止监听此文件的变化。
=> chore: stop listening if the file does not exist

src/main/kotlin/app/termora/SFTPPtyTerminalTab.kt, src/main/kotlin/app/termora/SSHTerminalTab.kt, src/main/kotlin/app/termora/SshClients.kt
如果这个 Host 配置了 Jump Hosts 和 Proxy ，那么会通过端口转发的方式连接到 SFTP。
=> feat: SFTP command support for Jump Hosts and Proxy

.github/workflows/linux-aarch64.yml
=> chore: linux-aarch64.yml

src/main/kotlin/app/termora/transport/FileSystemTabbed.kt
=> fix: dialog edge detection

src/main/kotlin/app/termora/SFTPPtyTerminalTab.kt, src/main/kotlin/app/termora/TerminalTabbed.kt, src/main/kotlin/app/termora/actions/OpenHostAction.kt, src/main/resources/i18n/messages.properties, src/main/resources/i18n/messages_zh_CN.properties, src/main/resources/i18n/messages_zh_TW.properties
当点击 `SFTP Command` 时检测电脑是否有 `SFTP` ，如果没有则报错提示。
=> feat: detecting SFTP program

src/main/kotlin/app/termora/keymap/KeymapManager.kt
=> chore: remove doubleShift shortcut

src/main/kotlin/app/termora/keymap/KeymapManager.kt
修复在有 Popup 窗口时，如果按某个快捷键也依然派发的问题。
=> fix: shortcut also triggers when Popup is available

src/main/kotlin/app/termora/HostTree.kt, src/main/resources/i18n/messages.properties, src/main/resources/i18n/messages_zh_CN.properties, src/main/resources/i18n/messages_zh_TW.properties
=> chore: improve contextmenu

src/main/kotlin/app/termora/SFTPPtyTerminalTab.kt, src/main/resources/i18n/messages.properties, src/main/resources/i18n/messages_zh_CN.properties, src/main/resources/i18n/messages_zh_TW.properties
将 SFTP 连接服务器时的算法顺序设置成和 apache-sshd 一致
=> feat: sftp HostKeyAlgorithms

src/main/kotlin/app/termora/SettingsOptionsPane.kt
=> feat: support system fonts

src/main/kotlin/app/termora/terminal/panel/TerminalDisplay.kt
修复终端光标在执行 `Ctrl + Shift + L` 后如果滚动页面会出现光标错乱。
=> fix: terminal cursor error

src/main/kotlin/app/termora/Database.kt, src/main/kotlin/app/termora/MyTabbedPane.kt, src/main/kotlin/app/termora/SettingsOptionsPane.kt, src/main/kotlin/app/termora/TerminalPanelFactory.kt, src/main/kotlin/app/termora/TermoraFrameManager.kt, src/main/kotlin/app/termora/terminal/panel/TerminalBlink.kt, src/main/kotlin/app/termora/terminal/panel/TerminalDisplay.kt, src/main/kotlin/app/termora/terminal/panel/TerminalPanel.kt, src/main/resources/i18n/messages.properties, src/main/resources/i18n/messages_zh_CN.properties, src/main/resources/i18n/messages_zh_TW.properties
支持 光标闪烁 和 [XTerm blink](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h4-Functions-using-CSI-_-ordered-by-the-final-character-lparen-s-rparen:CSI-Pm-m:Ps-=-5.1DFE)，光标闪烁需要在 `设置 - 终端 - 光标闪烁` 打开。
<br/>
=> feat: blink

src/main/kotlin/app/termora/WelcomePanel.kt, src/main/kotlin/app/termora/findeverywhere/FindEverywhereResult.kt, src/main/kotlin/app/termora/findeverywhere/FindEverywhereXList.kt
=> feat: FindEverywhere show more info

src/main/kotlin/app/termora/SSHTerminalTab.kt
=> fix: tunnels causes connection failure

src/main/kotlin/app/termora/terminal/panel/vw/SystemInformationVisualWindow.kt
=> fix: memory parsing error

src/main/kotlin/app/termora/Database.kt, src/main/kotlin/app/termora/SFTPTerminalTab.kt, src/main/kotlin/app/termora/SettingsOptionsPane.kt, src/main/kotlin/app/termora/TerminalTabbed.kt, src/main/kotlin/app/termora/TerminalTabbedManager.kt, src/main/kotlin/app/termora/TermoraFrame.kt, src/main/kotlin/app/termora/transport/SFTPAction.kt, src/main/resources/i18n/messages.properties, src/main/resources/i18n/messages_zh_CN.properties, src/main/resources/i18n/messages_zh_TW.properties
=> feat: support fixed SFTP tab

src/main/kotlin/app/termora/HostManager.kt, src/main/kotlin/app/termora/HostTreeNode.kt, src/main/kotlin/app/termora/NewHostTree.kt, src/main/kotlin/app/termora/RequestAuthenticationDialog.kt, src/main/kotlin/app/termora/SSHTerminalTab.kt, src/main/kotlin/app/termora/transport/SftpFileSystemPanel.kt, src/main/resources/i18n/messages.properties
=> feat: supports importing hosts from WindTerm

THIRDPARTY, build.gradle.kts, gradle/libs.versions.toml, src/main/kotlin/app/termora/NewHostTree.kt, src/main/resources/i18n/messages.properties, src/main/resources/i18n/messages_zh_CN.properties, src/main/resources/i18n/messages_zh_TW.properties
<br/>
用户应该选择 Xshell 的 Sessions 目录，否则无法导入。
=> feat: supports importing hosts from Xshell

src/main/kotlin/app/termora/NewHostTree.kt
支持导入 `MobaXterm.ini` 和 `*.mobaconf` 文件。
可以通过 MobaXterm 的 `Settings - Export configuration` 生成 `*.mobaconf` 文件。
=> feat: supports importing hosts from MobaXterm

src/main/kotlin/app/termora/NewHostTree.kt
需要从 `SecureCRT - Tools - Export Settings...` 导出 `xml` 文件。
=> feat: supports importing hosts from SecureCRT

src/main/kotlin/app/termora/NewHostTree.kt, src/main/resources/i18n/messages.properties, src/main/resources/i18n/messages_zh_CN.properties, src/main/resources/i18n/messages_zh_TW.properties
<br/>
需要在 FinalShell 中导出，导出完毕后即可在 Termora 导入。
=> feat: supports importing hosts from FinalShell

src/main/kotlin/app/termora/NewHostTree.kt
<br/>
从 electerm 的 `设置 - 设置同步 - 导出` 导出 `json` 文件，然后通过 Termora 导入。
=> feat: supports importing hosts from electerm

src/main/kotlin/app/termora/NewHostTree.kt
首先，`Win + R` 执行 `regedit` ，在地址栏输入 `Computer\HKEY_CURRENT_USER\Software\SimonTatham\PuTTY` 回车，对着 `PuTTY` 右键导出，导出格式选择 `reg` 然后在 Termora 导入即可。
<br/>
<br/>
=> feat: supports importing hosts from PuTTY

THIRDPARTY, build.gradle.kts, gradle/libs.versions.toml, src/main/kotlin/app/termora/ApplicationRunner.kt, src/main/kotlin/app/termora/Main.kt, src/main/kotlin/app/termora/SettingsOptionsPane.kt, src/main/kotlin/app/termora/TermoraRestarter.kt
=> feat: support restart

.github/workflows/osx-aarch64.yml, .github/workflows/osx-x86-64.yml, .github/workflows/winget.yml, build.gradle.kts
=> chore: automatically notarise macOS releases when released

src/main/kotlin/app/termora/TermoraRestarter.kt, src/main/kotlin/app/termora/actions/ActionManager.kt, src/main/kotlin/app/termora/actions/SFTPCommandAction.kt, src/main/kotlin/app/termora/keymap/KeymapImpl.kt, src/main/kotlin/app/termora/keymap/KeymapTableModel.kt, src/main/resources/i18n/messages.properties, src/main/resources/i18n/messages_zh_CN.properties, src/main/resources/i18n/messages_zh_TW.properties
增加 `Command/Ctrl + Shift + P` 打开 `SFTP Command`
=> feat: SFTP command add key shortcut

src/main/kotlin/app/termora/transport/FileTransportPanel.kt, src/main/kotlin/app/termora/transport/FileTransportTableModel.kt, src/main/kotlin/app/termora/transport/Transport.kt
=> feat: support sftp status

src/main/kotlin/app/termora/terminal/ControlSequenceIntroducerProcessor.kt, src/main/kotlin/app/termora/terminal/EscapeSequenceProcessor.kt, src/main/kotlin/app/termora/terminal/KeyEncoderImpl.kt, src/main/kotlin/app/termora/terminal/VisualTerminal.kt
=> fix: emacs shift key

src/main/kotlin/app/termora/terminal/TerminalLine.kt
=> fix: nano bg color

src/main/kotlin/app/termora/TerminalTabbed.kt, src/main/kotlin/app/termora/actions/OpenLocalTerminalAction.kt
=> feat: support edit host

src/main/kotlin/app/termora/terminal/ControlSequenceIntroducerProcessor.kt
=> fix: xterm-256 foreground & background color

src/main/kotlin/app/termora/sftp/SFTPTabbed.kt
=> feat: sftp contextmenu

src/main/kotlin/app/termora/TerminalPanelFactory.kt, src/main/kotlin/app/termora/terminal/ColorPaletteImpl.kt, src/main/kotlin/app/termora/terminal/panel/TerminalPanelKeyAdapter.kt
=> fix: emacs alt x

src/main/kotlin/app/termora/terminal/panel/vw/VisualWindowPanel.kt
=> feat: floating window supports stick

src/main/kotlin/app/termora/terminal/panel/TerminalPanelKeyAdapter.kt
=> chore: automatically jump to the bottom

.gitignore, src/main/kotlin/app/termora/ApplicationRunner.kt, src/main/kotlin/app/termora/Database.kt, src/main/kotlin/app/termora/SettingsOptionsPane.kt, src/main/kotlin/app/termora/TermoraFrameManager.kt, src/main/resources/i18n/messages.properties, src/main/resources/i18n/messages_zh_CN.properties, src/main/resources/i18n/messages_zh_TW.properties
=> feat: support system tray

src/main/kotlin/app/termora/WelcomePanel.kt
=> feat: Welcome search supports keyboard navigation

gradle/libs.versions.toml, src/main/kotlin/app/termora/Icons.kt, src/main/kotlin/app/termora/OptionPane.kt, src/main/kotlin/app/termora/sftp/FileSystemViewTable.kt, src/main/kotlin/app/termora/sftp/NativeFileIcons.kt, src/main/resources/i18n/messages.properties, src/main/resources/i18n/messages_zh_CN.properties, src/main/resources/i18n/messages_zh_TW.properties, src/main/resources/icons/file.svg, src/main/resources/icons/file_dark.svg
=> feat: SFTP file exists and prompts to overwrite

src/main/kotlin/app/termora/sftp/FileSystemViewTable.kt, src/main/kotlin/app/termora/sftp/TransportTableModel.kt
=> fix: SFTP add transport NPE

src/main/kotlin/app/termora/Database.kt, src/main/kotlin/app/termora/DeleteDataManager.kt, src/main/kotlin/app/termora/Host.kt, src/main/kotlin/app/termora/HostManager.kt, src/main/kotlin/app/termora/SettingsOptionsPane.kt, src/main/kotlin/app/termora/SimpleTree.kt, src/main/kotlin/app/termora/highlight/KeywordHighlight.kt, src/main/kotlin/app/termora/highlight/KeywordHighlightManager.kt, src/main/kotlin/app/termora/keymap/KeymapManager.kt, src/main/kotlin/app/termora/keymgr/KeyManager.kt, src/main/kotlin/app/termora/keymgr/OhKeyPair.kt, src/main/kotlin/app/termora/macro/Macro.kt, src/main/kotlin/app/termora/macro/MacroManager.kt, src/main/kotlin/app/termora/snippet/SnippetManager.kt, src/main/kotlin/app/termora/sync/GitSyncer.kt, src/main/kotlin/app/termora/sync/SafetySyncer.kt, src/main/kotlin/app/termora/sync/WebDAVSyncer.kt, src/main/resources/i18n/messages.properties, src/main/resources/i18n/messages_zh_CN.properties, src/main/resources/i18n/messages_zh_TW.properties
=> feat: improve sync

THIRDPARTY, build.gradle.kts, gradle/libs.versions.toml, src/main/kotlin/app/termora/EditHostOptionsPane.kt, src/main/kotlin/app/termora/Host.kt, src/main/kotlin/app/termora/HostOptionsPane.kt, src/main/kotlin/app/termora/RequestAuthenticationDialog.kt, src/main/kotlin/app/termora/SshClients.kt, src/main/kotlin/app/termora/TextField.kt, src/main/resources/i18n/messages.properties, src/main/resources/i18n/messages_zh_CN.properties, src/main/resources/i18n/messages_zh_TW.properties
支持 `ssh-agent`，在 Unix 环境使用 `SSH_AUTH_SOCK` ，在 Windows 环境则使用 `Pageant/Named pipe`
=> feat: SSH support ssh-agent

src/main/kotlin/app/termora/SshClients.kt, src/test/resources/sshd/Dockerfile
=> fix: SSH proxy not working in jump hosts

src/main/kotlin/app/termora/Database.kt, src/main/kotlin/app/termora/NotifyListener.kt, src/main/kotlin/app/termora/SettingsOptionsPane.kt, src/main/kotlin/app/termora/TermoraFrame.kt, src/main/kotlin/app/termora/TermoraFrameManager.kt, src/main/kotlin/app/termora/TextField.kt, src/main/resources/i18n/messages.properties, src/main/resources/i18n/messages_zh_CN.properties, src/main/resources/i18n/messages_zh_TW.properties
=> feat: support to set transparency

THIRDPARTY, build.gradle.kts, gradle/libs.versions.toml, src/main/kotlin/app/termora/ApplicationRunner.kt, src/main/kotlin/app/termora/sftp/FileSystemViewNav.kt, src/main/kotlin/app/termora/sftp/FileSystemViewPanel.kt, src/main/kotlin/app/termora/sftp/FileSystemViewTable.kt, src/main/kotlin/app/termora/sftp/FileSystemViewTableModel.kt, src/main/kotlin/app/termora/sftp/SFTPFileSystemViewPanel.kt, src/main/kotlin/app/termora/sftp/SFTPKit.kt, src/main/kotlin/app/termora/sftp/SFTPPanel.kt, src/main/kotlin/app/termora/sftp/SFTPTabbed.kt, src/main/kotlin/app/termora/sftp/Transport.kt, src/main/kotlin/app/termora/sftp/TransportTreeTableNode.kt, src/main/kotlin/app/termora/vfs2/sftp/MySftpFileObject.kt, src/main/kotlin/app/termora/vfs2/sftp/MySftpFileProvider.kt, src/main/kotlin/app/termora/vfs2/sftp/MySftpFileSystem.kt, src/main/kotlin/app/termora/vfs2/sftp/MySftpFileSystemConfigBuilder.kt, src/main/resources/i18n/messages.properties, src/main/resources/i18n/messages_zh_CN.properties, src/main/resources/i18n/messages_zh_TW.properties, src/test/kotlin/app/termora/SFTPTest.kt, src/test/kotlin/app/termora/SSHDTest.kt, src/test/kotlin/app/termora/vfs2/sftp/MySftpFileProviderTest.kt
=> feat: vfs2

src/main/kotlin/app/termora/sync/SyncManager.kt
=> fix: last sync time

src/main/kotlin/app/termora/sftp/FileSystemViewPanel.kt
=> fix: return to parent folder failure

src/main/kotlin/app/termora/snippet/SnippetAction.kt, src/main/kotlin/app/termora/snippet/SnippetPanel.kt
=> fix: snippet unescape

src/main/kotlin/app/termora/BackgroundManager.kt, src/main/kotlin/app/termora/terminal/panel/TerminalPanelKeyAdapter.kt
=> fix: Escape key

src/main/kotlin/app/termora/sftp/FileSystemProvider.kt, src/main/kotlin/app/termora/sftp/FileSystemViewNav.kt, src/main/kotlin/app/termora/sftp/FileSystemViewPanel.kt, src/main/kotlin/app/termora/sftp/FileSystemViewTable.kt, src/main/kotlin/app/termora/sftp/SFTPPanel.kt
=> fix: SFTP path not jumping on Windows

src/main/kotlin/app/termora/LocalTerminalTab.kt, src/main/kotlin/app/termora/TerminalTab.kt, src/main/kotlin/app/termora/terminal/PtyProcessConnector.kt, src/main/resources/i18n/messages.properties, src/main/resources/i18n/messages_zh_CN.properties, src/main/resources/i18n/messages_zh_TW.properties
=> chore: improve terminal close

src/main/kotlin/app/termora/keymap/Keymap.kt, src/main/kotlin/app/termora/sync/SafetySyncer.kt
=> fix: Keymap sync override

src/main/kotlin/app/termora/keymap/KeyShortcut.kt
=> chore: KeyShortcut toHuman text

src/main/kotlin/app/termora/Host.kt, src/main/kotlin/app/termora/HostOptionsPane.kt, src/main/kotlin/app/termora/HostTreeNode.kt, src/main/kotlin/app/termora/Icons.kt, src/main/kotlin/app/termora/NewHostTree.kt, src/main/kotlin/app/termora/actions/OpenHostAction.kt, src/main/resources/icons/microsoftWindows.svg, src/main/resources/icons/microsoftWindows_dark.svg
支持 RDP 协议（macOS、Windows）
会直接通过 `mstsc` 连接
会通过 [Windows App](https://apps.apple.com/app/windows-app/id1295203466) 连接，如果没有 [Windows App](https://apps.apple.com/app/windows-app/id1295203466) 则会提示下载。
----
默认情况下，当连接时会提示输入密码。如果密码已经在 Termora 中维护那么会自动设置到剪切板中，你只需要执行 `Ctrl/Command + V` 即可。
=> feat: support RDP protocol

src/main/resources/i18n/messages_zh_CN.properties, src/main/resources/i18n/messages_zh_TW.properties
https://github.com/TermoraDev/termora/issues/532#issuecomment-2826792801
=> chore: correct typos

src/main/kotlin/app/termora/NewHostTree.kt
=> fix: double-click to open the host

src/main/kotlin/app/termora/SshClients.kt
=> feat: support for compression algorithms

src/main/kotlin/app/termora/SshClients.kt
=> feat: support for signature algorithms

src/main/kotlin/app/termora/NewHostTree.kt
=> chore: folder count

src/main/kotlin/app/termora/snippet/SnippetTreeModel.kt
=> fix: snippet i18n

src/main/kotlin/app/termora/HostDialog.kt
=> fix: test connect

src/main/kotlin/app/termora/terminal/panel/TerminalPanelKeyAdapter.kt
=> chore: scroll to the bottom after pressed any key

src/main/kotlin/app/termora/TerminalPanelFactory.kt
=> fix: process Device Status Report (DSR)

src/main/kotlin/app/termora/sftp/FileSystemViewTable.kt, src/main/kotlin/app/termora/sftp/FileSystemViewTableModel.kt, src/main/kotlin/app/termora/sftp/PosixFilePermissionDialog.kt, src/main/kotlin/app/termora/vfs2/VFSWalker.kt, src/main/resources/i18n/messages.properties, src/main/resources/i18n/messages_zh_CN.properties, src/main/resources/i18n/messages_zh_TW.properties
=> feat: modify permissions to support recursion

src/main/kotlin/app/termora/sftp/SFTPFileSystemViewPanel.kt, src/main/kotlin/app/termora/sftp/SFTPTabbed.kt
=> feat: improve SFTP

src/main/kotlin/app/termora/sftp/FileSystemViewTable.kt
=> fix: SFTP drag and drop upload

src/main/kotlin/app/termora/sftp/SFTPAction.kt, src/main/kotlin/app/termora/sftp/SFTPFileSystemViewPanel.kt
=> chore: improve sftp tab

src/main/kotlin/app/termora/terminal/SelectionModel.kt, src/main/kotlin/app/termora/terminal/SelectionModelImpl.kt, src/main/kotlin/app/termora/terminal/panel/TerminalPanelMouseSelectionAdapter.kt
=> feat: support block selection

src/main/kotlin/app/termora/NewHostTree.kt
=> feat: support importing RDP protocol from CSV

src/main/kotlin/app/termora/Database.kt, src/main/kotlin/app/termora/SSHTerminalTab.kt, src/main/kotlin/app/termora/SettingsOptionsPane.kt, src/main/kotlin/app/termora/TerminalTab.kt, src/main/kotlin/app/termora/TerminalTabbed.kt, src/main/resources/i18n/messages.properties, src/main/resources/i18n/messages_zh_CN.properties, src/main/resources/i18n/messages_zh_TW.properties
=> feat: confirm tab close

src/main/kotlin/app/termora/terminal/ControlSequenceIntroducerProcessor.kt, src/test/resources/issue-564/Dockerfile
=> fix: Xterm Send Device Attributes (Primary DA)

src/main/kotlin/app/termora/HostOptionsPane.kt
#616
如果对着主机输入框粘贴时会去除粘贴板里面的不可见字符
=> chore: improve the host text field

src/main/kotlin/app/termora/snippet/SnippetAction.kt
=> fix: snippet `\` character escape

src/main/kotlin/app/termora/TermoraFrame.kt
=> fix: text cursor not working

src/main/kotlin/app/termora/plugin/internal/plugin/MarketplacePanel.kt, src/main/kotlin/app/termora/plugin/internal/plugin/PluginOption.kt, src/main/kotlin/app/termora/plugin/internal/plugin/PluginRepositoryDialog.kt, src/main/kotlin/app/termora/plugin/internal/plugin/PluginRepositoryManager.kt, src/main/kotlin/app/termora/plugin/marketplace/MarketplaceManager.kt, src/main/resources/i18n/messages.properties, src/main/resources/i18n/messages_zh_CN.properties, src/main/resources/i18n/messages_zh_TW.properties
=> feat: support plugin repository

src/main/kotlin/app/termora/SshClients.kt
因为在 macOS 通过 `launchd` 启动无法读取到自定义的 `SSH_AUTH_SOCK` 变量
如果自定义了 `SSH_AUTH_SOCK` ，那么用户可以在 `~/.termora/config/` 目录执行 `ln -s $SSH_AUTH_SOCK ssh_auth_sock.sock` 后 Termora 就可以正常使用 `SSH Agent`
在执行前，需要确保 `SSH_AUTH_SOCK` 已在环境变量中。如果 `SSH_AUTH_SOCK` 没有在环境变量中，命令则需要改成 `ln -s  sock的路径 ssh_auth_sock.sock`
=> chore: improve SSH_AUTH_SOCK reading on macOS

src/main/kotlin/app/termora/keyboardinteractive/KeyboardInteractiveDialog.kt, src/main/kotlin/app/termora/keyboardinteractive/TerminalUserInteraction.kt
=> fix: OTP dialog width

src/main/kotlin/app/termora/transfer/TransportPanel.kt
=> feat: transfer supports side button

build.gradle.kts
=> chore: linux deb

src/main/kotlin/app/termora/Host.kt, src/main/kotlin/app/termora/PtyHostTerminalTab.kt, src/main/kotlin/app/termora/highlight/NewKeywordHighlightDialog.kt, src/main/kotlin/app/termora/plugin/internal/sftppty/SFTPPtyTerminalTab.kt, src/main/kotlin/app/termora/plugin/internal/ssh/SSHHostOptionsPane.kt, src/main/resources/i18n/messages.properties, src/main/resources/i18n/messages_zh_CN.properties, src/main/resources/i18n/messages_zh_TW.properties
=> feat: support login scripts

build.gradle.kts
=> chore: disable opengl
